repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: name-tests-test
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    -   id: isort
        args: ["-m 3", "--trailing-comma", "-w 88"]
        exclude: elastalert/ruletypes/__init__.py
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      language_version: python3.6
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    - id: bandit
      exclude: tests/.*
      args: ['-b', '.bandit_baseline.json', '-c', '.bandit.yaml']
-   repo: https://github.com/Yelp/detect-secrets
    rev: v0.13.1
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*tests/.*|.*yelp/testing/.*|\.pre-commit-config\.yaml
