name: sklearn-svm-one
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - pip
  - python=3.7
  - pandas
  - numpy
  - scikit-learn=0.22
  - elasticsearch-dsl
  - click
  - pip:
    - mlflow>=1.8
